name: Despliegue PodoGonnet en GitHub Pages

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Instala dependencias
        working-directory: ./PodoFrontGonnet
        run: npm install

      - name: Construye la app
        working-directory: ./PodoFrontGonnet
        run: npm run build

      - name: Despliega en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PodoFrontGonnet/dist
